name: example-webkit-debug
#
# webkit support is currently experimental
# https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental
#
on:
  workflow_dispatch:

env:
  DEBUG: 'cypress:*'

jobs:
  webkit-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npx playwright@1.34.3 install-deps webkit
      - name: Cypress info and test
        uses: ./
        with:
          build: npm run info
          working-directory: examples/webkit
          browser: webkit

  webkit-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress info and test
        uses: ./
        with:
          build: npm run info
          working-directory: examples/webkit
          browser: webkit

  webkit-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress info and test
        uses: ./
        with:
          build: npm run info
          working-directory: examples/webkit
          browser: webkit
